### ISSUE TITLE
"ReferenceError: uri is not defined" when starting

### ISSUE THREAD

**Issue by mold** [Raynos/live-reload#3]
There is an undefined variable (uri) that prevents live-reload from starting. 

``` shell
> live-reload

/usr/local/lib/node_modules/live-reload/index.js:34
        , "reloading on files", uri)
                                ^
ReferenceError: uri is not defined
  at LiveReloadServer (/usr/local/lib/node_modules/live-reload/index.js:34:33)
  at Object.<anonymous> (/usr/local/lib/node_modules/live-reload/bin/reload.js:14:5)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:906:3
```

Everything seems to work as it should when I remove the reference to it.

**Comment by paulpflug** [comment]
+1

**Comment by Raynos** [comment]
Fixed in 1.1.0
