### ISSUE TITLE
Using //@ to indicate sourceURL pragmas is deprecated. Use //# instead

### ISSUE THREAD

**Issue by kodonnell** [Raynos/live-reload#8]
The above warnings appears many times in Firefox, which is making logging etc., unpleasant.

If I just grep '//@' in the live-reload package, I'm coming up with the the `browserify` module of `browserify-server` causing the issues. This appears to be because `browserify-server` is using an old version of `browserify` ... so remedying it might be simple with just an update?

**Comment by Bondifrench** [comment]
@Raynos @ianhoolihan  I second that, I got the following warnings in my chrome developer console:
![image](https://cloud.githubusercontent.com/assets/4905917/15205396/3be1529a-185a-11e6-932e-2e9e086b7591.png)

However a simple update is not enough.

More specifically, it seems the module [browserify-server](https://github.com/Raynos/browserify-server/blob/master/package.json) is using an [older version of Browserify](https://github.com/Raynos/node-browserify/blob/master/package.json#L3) `1.17.3` not in sync with the `browserify main repo` which is currently at version `13.0.1` 

The guys from Browserify told me that this issue has been resolved in November 2013 on their [side](https://github.com/substack/node-browserify/issues/1559#issuecomment-218637136).

However simply uninstalling the older version of `browserify` with the new one is not enough as it triggers the following error in node:

```
c:\Users\London\Apps\FinviewsApp\node_modules\live-reload\node_modules\browserify-server\index.js:22
    bundle.register(".html", handleHtml)
           ^

TypeError: bundle.register is not a function
    at createBundle (c:\Users\London\Apps\FinviewsApp\node_modules\live-reload\node_modules\browserify-server\index.js:22:12)
    at bundle (c:\Users\London\Apps\FinviewsApp\node_modules\live-reload\node_modules\browserify-server\index.js:8:18)
    at LiveReloadServer (c:\Users\London\Apps\FinviewsApp\node_modules\live-reload\index.js:18:20)
    at Object.<anonymous> (c:\Users\London\Apps\FinviewsApp\node_modules\live-reload\bin\reload.js:14:5)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
```

The new version of Browserify does not have however a `register` function, that's why it's triggering the error. Unfortunately we are reaching the limits of my investigating skills. @Raynos Would you know what the equivalent of `register` would be now, using the newest version of `node-browserify`?
